version: 2.1

jobs:
  hello-world:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Say Hello
          command: |
            echo "First Job"
  # The Frontend job
  frontend-lint:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      # Install project dependencies
      - run:
          name: Install local dependencies
          command: cd udagram-frontend && npm install

      - run:
          name: Testing
          command: cd udagram-frontend && npm run build

  backend-lint:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      # Install project dependencies
      - run:
          name: Install local dependencies
          command: cd udagram-api && npm install

      - run:
          name: Testing
          command: cd udagram-api && npm run build

  deploy-code:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - run:
          name: Install system dependencies
          command: |
            apk add --no-cache curl
            apk add --no-cache --upgrade bash
            apk add --no-cache --update npm
            pip3 install awscli
      - run:
          name: Frontend Build
          command: |
            cd udagram-frontend
            npm install
            npm run build
      - run:
          name: S3 Bucket
          command: |
            aws s3 sync ./udagram-frontend/www s3://${BUCKET_NAME}/

workflows:
  default:
    jobs:
      - hello-world

      - frontend-lint:
          requires:
            - hello-world

      - backend-lint:
          requires:
            - frontend-lint
