version: 2.1

jobs:
  hello-world:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Say Hello
          command: |
            echo "First Job"
  # The Frontend job
  frontend-lint:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      # Install project dependencies
      - run:
          name: Install local dependencies
          command: npm run frontend:install

      - run:
          name: Testing
          command: npm run frontend:build

  backend-lint:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      # Install project dependencies
      - run:
          name: Install local dependencies
          command: npm run backend:install

      - run:
          name: Testing
          command: npm run backend:build

  deploy-frontend-code:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - run:
          name: Install system dependencies
          command: |
            apk add --no-cache curl
            apk add --no-cache --upgrade bash
            apk add --no-cache --update npm
            pip3 install awscli
      - run:
          name: Frontend Build
          command: |
            npm run frontend:install
            npm run frontend:build
      # - run:
      #     name: S3 Bucket
      #     command: |
      #       aws s3 sync ./udagram-frontend/www s3://${BUCKET_NAME}/

  deploy-backend-code:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - run:
          name: Install system dependencies
          command: |
            apk add --no-cache curl
            apk add --no-cache --upgrade bash
            apk add --no-cache --update npm
            pip3 install awscli
      - run:
          name: Backend Install
          command: npm run backend:install
      - run:
          name: Backend Build
          command: npm run backend:build
      - run:
          name: Deploy Backend
          command: |
            cd udacity-api/www/
            eb deploy

workflows:
  default:
    jobs:
      - hello-world

      - frontend-lint:
          requires:
            - hello-world

      - backend-lint:
          requires:
            - hello-world

      - deploy-frontend-code:
          requires:
            - frontend-lint

      - deploy-backend-code:
          requires:
            - backend-lint
